#%RAML 1.0 NamedExample
value:
  - 
    id: 1
    name: "Eduardo"
    lastName: "Villagomez"
    age: 19
    matter: "matematica"
    qualification: 9
    gender: "masculino"
    status: "aprobado"
  - 
    id: 2
    name: "Jorge"
    lastName: "Gutierrez"
    age: 22
    matter: "lengua"
    qualification: 3
    gender: "masculino"
    status: "desaprobado"
  - 
    id: 3
    name: "Lia"
    lastName: "Rodriguez"
    age: 20
    matter: "fisica"
    qualification: 8
    gender: "femenino"
    status: "aprobado"