#%RAML 1.0 DataType
type: object
properties:
  name:
    type: string
  lastName:
    type: string
  age:
    type: integer
  matter:
    type: string
  qualification:
    type: integer
  gender:
    type: string
  status:
    type: string